### PR TITLE
Add mention of party and lightning talks

### LINKED ISSUE #27: Add party to the program
I think we can copy something from previous year's website

Just one note: All times are hidden (since talks don't have times) but talks are sorted by time anyways... so the party can appear last by putting for instance 20:00, which is probably the starting time anyways :)

### PR DESCRIPTION
**Pull request by benjaoming**
Fixes #27

### CODE REVIEW

**Review by benjaoming — COMMENTED** [review]
Comments and input most welcome, will just merge for now :)

**Comment by jvzammit** [comment]
LGTM

Perhaps set an earlier than `Thursday 20:00` submission deadline for online lightning talks? I think based on last year, organisers already had their hands full by that time last year. Still, up to you.

**Comment by benjaoming** [comment]
> Perhaps set an earlier than Thursday 20:00 submission deadline for online lightning talks?

Good point. It's also putting extra efforts into the hands of the video/streaming team, and their preps are done earlier.

Maybe Tuesday 20:00 is better.

I'm not sure if we got any online submissions last year. I don't think so. It'd be very easy to miss.

**Comment by jvzammit** [comment]
> Maybe Tuesday 20:00 is better.

Agreed.

> I'm not sure if we got any online submissions last year. I don't think so. It'd be very easy to miss.

It's a good thing it's being offered though, might give the opportunity to someone who is unable to physically make it to CPH.

**Pull request merged**
