### PR TITLE
Add new logo and make menu work on mobile displays

### PR DESCRIPTION
**Pull request by benjaoming**
New design:

image

### CODE REVIEW

**Review by valberg — APPROVED** [review]
😍

**Comment by benjaoming** [comment]
Had to do a mini adjustment because the emoji with the clinking glasses didn't look good on my screen

image

I think emojis are really dependent on the installation so no guarantees, but LMK if they somehow look odd :)

**Comment by benjaoming** [comment]
Also, suggestions for different emojis are always welcome, these are really random, just wanted to add something representative of the event :)

**Comment by benjaoming** [comment]
The new logo is sooooooooo nice, I love that it's in SVG and has transparency to make it work so well on top of the menu and title bar

**Comment by benjaoming** [comment]
Kudos @aspigirlcodes :heart:

**Pull request merged**
