### PR TITLE
Get the speaker list going

### PR DESCRIPTION
**Pull request by benjaoming**
Pending a few more things for tomorrow

### CODE REVIEW

**Comment by benjaoming** [comment]
@valberg @jvzammit reviews of course welcome, but I'm too excited to wait :heart: 

There's hopefully a talk or two more incoming today, but I think we're getting close to a couple of public toots/tweets :)

**Comment by jvzammit** [comment]
@benjaoming Are we keeping a sheet of submissions/speakers like last year? That would help with visibility, thanks!

**Comment by benjaoming** [comment]
@jvzammit yes, I'll send it over if you're joining the CFP group? :blush:  We haven't kept this information in public so that both CFP "panel" and speakers have discretion if needed.

**Comment by jvzammit** [comment]
I'll PM you in zulip

**Pull request merged**
