### PR TITLE
Clean up the site, so it's ready for 2023 content

### PR DESCRIPTION
**Pull request by benjaoming**

### CODE REVIEW

**Comment by benjaoming** [comment]
@jvzammit just sending you a notification here that some first few bits are solved here :)

**Review by jvzammit — APPROVED** [review]
Lot of work cleaning up, thanks @benjaoming 

Also nice colour change!

To be frank I didn't review all code changes, just ran it locally and browsed a bit through the pages. LGTM (mostly TBA's of course, but still).

**Comment by benjaoming** [comment]
I'll try to get this deployed automatically, same fashion as the former website...

I wanna try some other color alternatives, too.

**Comment by benjaoming** [comment]
Okay, I think I got the deployment ready.. DNS, certificate, webhook...

**Pull request merged**
